[22_3] Improve Chinese Translation in Graphics Mode
MoganLab/mogan pull request #872
Opened 2023-08-01 16:36 UTC by Oyyko

我使用字典序重新排列了整个文件。因此git diff可能较多。

2023-08-02 14:30 UTC, darcy-shen commented
这个需要单独提一个排序的pr，然后再提增加翻译的pr

现在这样我无法review增加的那些翻译

2023-08-02 14:30 UTC, da-liii requested changes
拆成两个pr，一个只做排序，另外一个只新增翻译

2023-08-03 03:10 UTC, Oyyko commented
OK. Close this now.

2023-08-03 03:10 UTC, closed without merging

2023-08-03 04:27 UTC, Oyyko commented
> 这个需要单独提一个排序的pr，然后再提增加翻译的pr
> 
> 现在这样我无法review增加的那些翻译

也许下次遇到类似情况可以一个PR里面包括两个commit？ 每一个commit的修改是单独可见的。

2023-08-03 04:52 UTC, darcy-shen commented
这样也是可以的