[50_1] new entry for mogan draw
MoganLab/mogan pull request #917
Opened 2023-08-09 05:09 UTC by Oyyko

2023-08-09 05:10 UTC, Oyyko commented
About CI: should I put CI in another task like 50_2?

2023-08-09 05:20 UTC, darcy-shen commented on xmake.lua
> +    if is_plat("macosx") or is_plat("linux") then
should be simplified here

2023-08-09 05:20 UTC, darcy-shen commented on xmake.lua
> +    if is_plat("macosx") then
should be removed

2023-08-09 05:20 UTC, darcy-shen commented on xmake.lua
> +    if is_plat("mingw") then
should be removed

2023-08-09 05:20 UTC, darcy-shen commented on xmake.lua
> +    if is_plat("mingw") and is_mode("releasedbg") then
should be removed

2023-08-09 05:21 UTC, darcy-shen commented on xmake.lua
> +    if is_plat("macosx") then
should be removed

2023-08-09 05:21 UTC, darcy-shen commented on xmake.lua
> +        if is_plat("macosx") and is_arch("arm64") then
remove it

2023-08-09 05:21 UTC, darcy-shen commented on xmake.lua
> +        if is_plat("mingw") then
remove it

2023-08-09 05:22 UTC, darcy-shen commented on xmake.lua
> +        if is_plat("mingw") then
only reserve linux

2023-08-09 05:22 UTC, darcy-shen commented
> Should I put CI in another task like 50_2?

Yes

> Should the CI of mogan draw be in the same file of mogan research?

No

2023-08-09 06:09 UTC, Oyyko commented on xmake.lua
> +    if is_plat("macosx") or is_plat("linux") then
fixed

2023-08-09 06:09 UTC, Oyyko commented
Fixed.

2023-08-09 14:54 UTC, darcy-shen commented on src/Mogan/Draw/draw.cpp
> +#ifdef AQUATEXMACS
这个和macos有关，需要移除

2023-08-09 14:55 UTC, darcy-shen commented on src/Mogan/Draw/draw.cpp
> +#ifdef OS_MINGW
remove it

2023-08-09 14:55 UTC, darcy-shen commented on src/Mogan/Draw/draw.cpp
> +#if defined(X11TEXMACS) && defined(MACOSX_EXTENSIONS)
remove it

2023-08-09 14:56 UTC, darcy-shen commented on src/Mogan/Draw/draw.cpp
> +#ifdef OS_MINGW
移除即可

2023-08-09 14:57 UTC, darcy-shen commented on src/Mogan/Draw/draw.cpp
> +#ifdef OS_HAIKU
移除即可

2023-08-09 14:57 UTC, darcy-shen commented on src/Mogan/Draw/draw.cpp
> +#if defined(X11TEXMACS) && defined(MACOSX_EXTENSIONS)
remove it

2023-08-09 15:51 UTC, Oyyko commented
OK. Removed MacOS, OS_MINGE, OS_HAIKU code.

2023-08-10 12:06 UTC, jingkaimori requested changes
Please decrease duplicated code between `research` and `draw` target

2023-08-10 12:06 UTC, jingkaimori commented on xmake.lua
> +    on_config(function (target)
glue generator should be put into `libmogan` target to avoid generating glue repeatly

2023-08-10 12:06 UTC, jingkaimori commented on xmake.lua
> +    local TeXmacs_files = {
This list of file could be put at global namespace

2023-08-10 12:06 UTC, jingkaimori commented on xmake.lua
> +        os.cp ("TeXmacs/misc/images/texmacs.svg",
these copy of icon should be extract to function, and invoke this function at `research` and `draw` application

2023-08-10 13:17 UTC, darcy-shen commented
> Please decrease duplicated code between research and draw target

Let the pr compiles and ci pass first. I think the duplicated code is ok for this pr.

2023-08-10 13:33 UTC, jingkaimori commented on xmake.lua
> +    on_config(function (target)
> Let the pr compiles and ci pass first. I think the duplicated code is ok for this pr.

At least this part should be simplified to reduce time wasting during ci run.

2023-08-10 13:35 UTC, darcy-shen commented on xmake.lua
> +    on_config(function (target)
reasonable, let us set a higher standard for @Oyyko ^_^

2023-08-12 07:26 UTC, Oyyko commented on xmake.lua
> +        os.cp ("TeXmacs/misc/images/texmacs.svg",
Due to what seems to be a limitation in xmake where it doesn't directly support defining global functions (global variables defined in xmake.lua are not loaded when entering the after_install function), I have opted to use the modular approach. According to [https://tboox.org/cn/2020/07/18/quickstart-12-custom-scripts/](https://tboox.org/cn/2020/07/18/quickstart-12-custom-scripts/) this method appears to be the standard approach.

2023-08-12 07:28 UTC, Oyyko commented
> Please rebase your branch on the latest `branch-1.2`, we just made massive changes.

It seems that git rebase will produce many "git diff" in https://github.com/XmacsLabs/mogan/pull/917/files...

2023-08-12 07:29 UTC, Oyyko commented on xmake.lua
> +    on_config(function (target)
Fine.

2023-08-12 07:31 UTC, Oyyko commented on xmake.lua
> +    local TeXmacs_files = {
Fine. Although I think that the so-called "global variables" in xmake.lua can not be seen in the script field of xmake.lua. It still works because we don't need to visit TeXmacs_files in script field(脚本域).

2023-08-12 07:32 UTC, Oyyko commented on xmake.lua
> +        os.cp ("TeXmacs/misc/images/texmacs.svg",
You can try defining global variables or functions in xmake.lua, but you will find that they are not visible in the script scope. I suspect this is because when executing the script scope, xmake.lua is not executed from the beginning. Therefore, I opted for the modular approach, using import to make the script scope load the relevant information.

2023-08-12 10:44 UTC, Oyyko commented
@darcy-shen @jingkaimori Hi. Please give me some feedback if you're free.

2023-08-13 04:18 UTC, Oyyko commented
Closed Now. Change to #932 .

2023-08-13 04:18 UTC, closed without merging