[36_1] change linker to accelerate building
MoganLab/mogan pull request #958
Opened 2023-08-25 02:09 UTC by jingkaimori

2023-08-27 10:40 UTC, darcy-shen commented
这个和Windows平台有什么关系么？为什么是 项目36?

2023-08-27 11:49 UTC, jingkaimori commented
这个修改和xmake关系大，本来应该放到项目3里面

2023-08-27 11:54 UTC, darcy-shen commented
> 这个修改和xmake关系大，本来应该放到项目3里面

新建一个项目吧，项目3已经完结了

2023-09-20 03:26 UTC, Charonxin approved these changes

2023-09-20 03:26 UTC, Charonxin commented
Can we count the time it takes to replace the linker?

2023-09-20 06:37 UTC, darcy-shen commented
@Charonxin 这个ci这么多fail为什么要approve？

2023-09-20 06:39 UTC, Charonxin commented
> @Charonxin 这个ci这么多fail为什么要approve？

可能因为没好好做code review..

2023-09-20 06:45 UTC, Charonxin commented
看上去好像是新引入的`database-test`的问题吗？

2023-09-20 07:34 UTC, darcy-shen commented
mingw的ci还有问题，仅仅是为了构建快一些的话，目前 ci 还需要改进一下，我觉得暂时没有必要在链接器这块更改相关配置

另外，如 @Charonxin 所说，具体能够加速，前后需要有对比

2023-09-20 07:36 UTC, darcy-shen requested changes
CI failed on mingw, and comparison needed

2023-09-20 10:10 UTC, closed without merging